/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppDepensesRouteImport } from './routes/_app.depenses'
import { Route as AppProduitsRouteImport } from './routes/_app.produits'
import { Route as AppTableauDeBordRouteImport } from './routes/_app.tableau-de-bord'
import { Route as AppVentesNouvelleRouteImport } from './routes/_app.ventes.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppProduitsRoute = AppProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppRoute,
} as any)
const AppTableauDeBordRoute = AppTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => AppRoute,
} as any)
const AppVentesNouvelleRoute = AppVentesNouvelleRouteImport.update({
  id: '/ventes/nouvelle',
  path: '/ventes/nouvelle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/clients': typeof AppClientsRoute
  '/depenses': typeof AppDepensesRoute
  '/produits': typeof AppProduitsRoute
  '/tableau-de-bord': typeof AppTableauDeBordRoute
  '/ventes/nouvelle': typeof AppVentesNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/clients': typeof AppClientsRoute
  '/depenses': typeof AppDepensesRoute
  '/produits': typeof AppProduitsRoute
  '/tableau-de-bord': typeof AppTableauDeBordRoute
  '/ventes/nouvelle': typeof AppVentesNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/depenses': typeof AppDepensesRoute
  '/_app/produits': typeof AppProduitsRoute
  '/_app/tableau-de-bord': typeof AppTableauDeBordRoute
  '/_app/ventes/nouvelle': typeof AppVentesNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/clients'
    | '/depenses'
    | '/produits'
    | '/tableau-de-bord'
    | '/ventes/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/clients'
    | '/depenses'
    | '/produits'
    | '/tableau-de-bord'
    | '/ventes/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/clients'
    | '/_app/depenses'
    | '/_app/produits'
    | '/_app/tableau-de-bord'
    | '/_app/ventes/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depenses': {
      id: '/_app/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produits': {
      id: '/_app/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AppProduitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tableau-de-bord': {
      id: '/_app/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AppTableauDeBordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ventes/nouvelle': {
      id: '/_app/ventes/nouvelle'
      path: '/ventes/nouvelle'
      fullPath: '/ventes/nouvelle'
      preLoaderRoute: typeof AppVentesNouvelleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppProduitsRoute: typeof AppProduitsRoute
  AppTableauDeBordRoute: typeof AppTableauDeBordRoute
  AppVentesNouvelleRoute: typeof AppVentesNouvelleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppProduitsRoute: AppProduitsRoute,
  AppTableauDeBordRoute: AppTableauDeBordRoute,
  AppVentesNouvelleRoute: AppVentesNouvelleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
